In [ ]:
# import numpy as np
# x = np.array([[2,5,8,9], [8,9,6,5]])
# x.shape

In [ ]:
# y = np.array(['a' , 'v' , 'x'])
# y

In [1]:
import numpy as np
x = np.array(5)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(type(x))

5
()
0
int32
<class 'numpy.ndarray'>


In [2]:
# type(x)
print(x.shape)
print(x.ndim)
x.dtype

()
0


dtype('int32')

In [6]:
my_arr = np.arange(45).reshape(9,5).astype('int')
print(my_arr)
print(my_arr.ndim)
my_arr.astype('float')
print(my_arr)
x = np.array([1,2,3] , dtype = 'float')
x

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


array([1., 2., 3.])

In [24]:
arr_3d = np.arange(45).reshape(5,3,3)

print(arr_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [7]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a[0:7:2] #starts from 0 end before 7 with step 2

array([0, 2, 4, 6])

In [15]:
bg_array = np.arange(75).reshape(15 , 5) * 3
bg_array

array([[  0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27],
       [ 30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57],
       [ 60,  63,  66,  69,  72],
       [ 75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102],
       [105, 108, 111, 114, 117],
       [120, 123, 126, 129, 132],
       [135, 138, 141, 144, 147],
       [150, 153, 156, 159, 162],
       [165, 168, 171, 174, 177],
       [180, 183, 186, 189, 192],
       [195, 198, 201, 204, 207],
       [210, 213, 216, 219, 222]])

In [17]:
bg_array[:7:2]

array([[  0,   3,   6,   9,  12],
       [ 30,  33,  36,  39,  42],
       [ 60,  63,  66,  69,  72],
       [ 90,  93,  96,  99, 102]])

In [18]:
b = np.arange(24).reshape(6,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
bg_array

array([[  0,   3,   6,   9,  12],
       [ 15,  18,  21,  24,  27],
       [ 30,  33,  36,  39,  42],
       [ 45,  48,  51,  54,  57],
       [ 60,  63,  66,  69,  72],
       [ 75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102],
       [105, 108, 111, 114, 117],
       [120, 123, 126, 129, 132],
       [135, 138, 141, 144, 147],
       [150, 153, 156, 159, 162],
       [165, 168, 171, 174, 177],
       [180, 183, 186, 189, 192],
       [195, 198, 201, 204, 207],
       [210, 213, 216, 219, 222]])

In [20]:
# b[start:end,start:end]
new_b = b[4:5,2:3]
print(new_b)
print(new_b.shape)
new_b.ndim

[[18]]
(1, 1)


2

In [21]:
assignment = np.arange(54).reshape(6,9)
assignment

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53]])

In [22]:
assignment[3:,5: ]

array([[32, 33, 34, 35],
       [41, 42, 43, 44],
       [50, 51, 52, 53]])

In [23]:
array_3d = np.arange(36).reshape(6,6)
array_3d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [25]:
array_3d[0:2,0:4]

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

In [29]:
b = np.arange(27).reshape(3,3,3)
print(b[1:2,0:1,0:1].ndim)
b.ndim

3


3

In [30]:
index = np.arange(36).reshape(6,6)
index

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
index[3,3] = 8
index

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20,  8, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
rep_3d = np.arange(27).reshape(3,3,3)
rep_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
rep_3d[1, 0:2, 2:] = 5
rep_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10,  5],
        [12, 13,  5],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
arr_3d[1:2,1:3,1:2]

array([[[13],
        [16]]])

In [36]:
assignment = np.arange(75).reshape(5,3,5)
assignment

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [37]:
assignment[3,2,2] = 100
assignment

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56, 100,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]]])

In [38]:
x = np.ones((10,10))
x[1:9 , 1:9]= 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])