In [2]:
import numpy as np

In [3]:
a = np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b = np.arange(12,24).reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
a+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [8]:
a^b

array([[12, 12, 12, 12],
       [20, 20, 20, 20],
       [28, 28, 28, 28]], dtype=int32)

In [9]:
b^a

array([[12, 12, 12, 12],
       [20, 20, 20, 20],
       [28, 28, 28, 28]], dtype=int32)

Transpose of Matrix A

In [10]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Dot Product

In [11]:
a*b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [12]:
np.cos(np.pi)

-1.0

In [13]:
a/b

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [14]:
b/a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf, 13.        ,  7.        ,  5.        ],
       [ 4.        ,  3.4       ,  3.        ,  2.71428571],
       [ 2.5       ,  2.33333333,  2.2       ,  2.09090909]])

.
.
.
.
Cross Product
.
.
.
.

(3 x 4) x (3 x 4)

In [15]:
a@b

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)


(4 x 3) x (3 x 4)

In [16]:
a.T@b

array([[224, 236, 248, 260],
       [272, 287, 302, 317],
       [320, 338, 356, 374],
       [368, 389, 410, 431]])

In [17]:
a @ b.T

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [18]:
a.dot(b.T)

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [19]:
a.diagonal()

array([ 0,  5, 10])

In [20]:
a.cumsum(1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [21]:
a.cumsum(0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [22]:
np.size(a)

12

In [23]:
a.size

12

In [24]:
c = np.arange(5)
print(c)
c < 2

[0 1 2 3 4]


array([ True,  True, False, False, False])

In [25]:
def exp(x):
    return x < 3 or x > 3
print(exp(c))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
np.vectorize(exp)(c)

array([ True,  True,  True, False,  True])

In [29]:
check = c < 3
c[check]

array([0, 1, 2])

In [30]:
np.size(c[check])

3

In [31]:
c[check].size

3

In [32]:
n = np.arange(25)
print(n)
print(np.sum(n<10))
print(np.sum(n[n<10]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
10
45


In [33]:
a = np.arange(16).reshape(4,4)
even = a % 2 == 0
print(a,'\n')
print(a[even])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 0  2  4  6  8 10 12 14]


In [34]:
a = np.arange(16).reshape(4,4)
odd = a % 2 == 1
print(a,'\n')
print(a[odd])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 1  3  5  7  9 11 13 15]


In [35]:
a = np.arange(16).reshape(4,4)
print(a[a % 2 == 0])

print()
print(np.sum(a[a%2==0]))

[ 0  2  4  6  8 10 12 14]

56


In [37]:
z = a.reshape(16)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
a.flatten(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
a.flatten(1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


array([ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15])

In [42]:
a.flatten('F')

array([ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15])